server.port=8080
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB
spring.web.resources.static-locations=classpath:/static/
deepfake.infer-script=C:/Users/Flippy/Downloads/Deepfake-detection-master/Deepfake-detection-master/infer.py
deepfake.python-cmd=python3
deepfake.timeout-seconds=60
